version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: elvis
      MINIO_ROOT_PASSWORD: Rudeboy7
    volumes:
      - minio-data:/data

volumes:
  minio-data:
